<a href="https://colab.research.google.com/github/meetptl04/mpmc_fakeprofile_project/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello , I am excited to learn pyTorch")

Hello , I am excited to learn pyTorch


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


#Introduction to Tensors

###Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # number of dimensions : scalar has no dimension

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random tensors

Why random tensors are important?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust hose random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6292, 0.6747, 0.5933, 0.7696],
        [0.4396, 0.6055, 0.7039, 0.6786],
        [0.8791, 0.5195, 0.5607, 0.6051]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height , width , colour channels (R,G,B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_image_size_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [26]:
# torch.arange()
one_to_ten = torch.arange(start = 1, end = 11,step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

**Note:** Tensor datatypes is one of 3 big errors you'll run into with pytorch and deep learning .

1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [37]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

### Getting information from tensors

1. Tensors not right datatypes : `tensor.dtype`
2. Tensors not right shape : `tensor.shape`
3. Tensors not on the right device : `tensor.device`

In [38]:
# Create a tensor

some_tensor = torch.rand([3,4])
some_tensor

tensor([[0.3438, 0.4132, 0.0398, 0.6803],
        [0.8414, 0.9549, 0.9559, 0.9048],
        [0.1070, 0.2286, 0.1208, 0.6591]])

In [40]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [41]:
some_tensor.size() # This is function

torch.Size([3, 4])

In [42]:
print(some_tensor)
print(f"Datatype of tesors : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.3438, 0.4132, 0.0398, 0.6803],
        [0.8414, 0.9549, 0.9559, 0.9048],
        [0.1070, 0.2286, 0.1208, 0.6591]])
Datatype of tesors : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Matrix multiplication
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The **resulting matrix** has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

- **Note**: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

In [44]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [47]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.04 ms, sys: 25 µs, total: 2.07 ms
Wall time: 2.35 ms


tensor(14)

In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.07 ms, sys: 3 µs, total: 1.08 ms
Wall time: 992 µs


tensor(14)

### One of the most common errors in deep learning (shape errors)

## Finding the min, max, mean, sum, etc (aggregation)

In [60]:
# Create a tensor
x = torch.arange(0, 100, 10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [54]:
# min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [55]:
# max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [61]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [66]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [67]:
# sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Positional min/max

In [68]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Reshaping , stacking , squeezing and unsqueezing tensors

https://www.learnpytorch.io/00_pytorch_fundamentals/#reshaping-stacking-squeezing-and-unsqueezing